---
# file: tasks/configure.yml

- name: ensure that dispatcher configuration files are ok
  template:
    src: '{{ item }}.j2'
    dest: '{{ dispatcheranylocation }}/{{ item }}'
    owner: '{{ webserveruser }}'
    group: '{{ webservergroup }}'
    mode: 0640
  with_items:
    - '{{ dispatcherconfigset }}'
  notify:
  - restart httpd
  become: True
- meta: flush_handlers

- name: ensure that main dispatcher configuration is ok
  template:
    src: dispatcher.conf.j2
    dest: '{{ apachedir }}/conf.d/dispatcher.conf'
    owner: '{{ webserveruser }}'
    group: '{{ webservergroup }}'
    mode: 0640
  notify:
  - restart httpd
  become: True
- meta: flush_handlers
<<<<<<< HEAD
<<<<<<< HEAD
  become: True
=======
  become: True
>>>>>>> parent of a991f6c... Include Apache-httpd installation
=======
  become: True
>>>>>>> parent of a991f6c... Include Apache-httpd installation
