---
# file: tasks/configure.yml

- name: ensure that httpd.conf is correct
  become: true
  template:
    src: '{{ ansible_os_family }}_httpd.conf.j2'
    dest: "{{ httpd_conf_file }}"
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    backup: true
  notify:
  - restart apache

- block:

  - name: Prepare ssl for apache
    include_tasks: '{{ ansible_os_family }}_ssl.yml'
    when:
      - use_native_cert | bool

<<<<<<< HEAD
=======
  - name: Change cert source path
    set_fact:
      cert_source_file: '{{ native_cert_source_file }}'
      key_source_file: '{{ native_key_source_file }}'
    when:
      - use_native_cert | bool

>>>>>>> f9ead3106fea77e165328aded936fa6286340678
  - name: Copy certificate for host
    copy:
      remote_src: '{{ use_native_cert | bool }}'
      src: '{{ cert_source_file }}'
      dest: '{{ cert_dest_file }}'
      owner: '{{ web_server_user }}'
      group: '{{ web_server_group }}'
    notify: restart apache

  - name: Copy key for host
    copy:
      remote_src: '{{ use_native_cert | bool }}'
      src: '{{ key_source_file }}'
      dest: '{{ key_dest_file }}'
      owner: '{{ web_server_user }}'
      group: '{{ web_server_group }}'
    notify: restart apache

  become: true
  when: web_server_ssl | bool
