---
# file: tasks/configure.yml

- name: ensure that dispatcher configuration files are ok
  template:
    src: '{{ item }}.j2'
    dest: '{{ dispatcher_any_location }}/{{ item }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0640
  with_items:
    - '{{ dispatcher_config_set }}'
  notify:
  - restart httpd
  become: True
- meta: flush_handlers

- name: ensure that main dispatcher configuration is ok
  template:
    src: dispatcher.conf.j2
    dest: '{{ apache_dir }}/conf.d/dispatcher.conf'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0640
  notify:
  - restart httpd
  when: ansible_facts['os_family'] == 'Redhat'
  become: True
- meta: flush_handlers

- name: ensure that main dispatcher configuration is ok
  template:
    src: dispatcher.conf.j2
    dest: '{{ apache_dir }}/sites-enabled/dispatcher.conf'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0640
  notify:
  - restart httpd
  when: ansible_facts['os_family'] == 'Debian'
  become: True
- meta: flush_handlers
