---
- block:
  - name: Add dispatcher.load
    template:
      src: 'dispatcher.load.j2'
      dest: '{{ apache_dir }}/mods-available/dispatcher.load'
      owner: 'root'
      group: 'root'
      mode: 0644

  - name: Create links
    file:
      src: '{{ link_item.src }}'
      dest: '{{ link_item.dest }}'
      state: link
    loop:
      - src: /usr/lib/apache2/modules
        dest: /etc/apache2/modules
      - src: '{{ apache_dir }}/mods-available/dispatcher.load'
        dest: '{{ apache_dir }}/mods-enabled/dispatcher.load'
      - src: '{{ apache_dir }}/mods-available/dispatcher.conf'
        dest: '{{ apache_dir }}/mods-enabled/dispatcher.conf'
      - src: '/var/log/apache2'
        dest: '{{ apache_dir }}/logs'
        state: link
    loop_control:
      loop_var: link_item
    notify: restart apache
  become: true
