---
- block:
  - name: Install python-openssl
    package:
      name: python-openssl
      state: present
    register: installed_packages
    until: installed_packages is succeeded

  - name: Create folders for certs
    file:
      path: '{{ certs_path }}/private'
      state: directory
      mode: 0777

  - name: Create folders for certs
    file:
      path: '{{ certs_path }}/certs'
      state: directory
      mode: 0777

  - name: Create private certificate
    openssl_privatekey:
      path: '{{ certs_path }}/private/{{ inventory_hostname }}.key'
      size: 4096
      owner: '{{ web_server_user }}'

  - name: Create CSR
    openssl_csr:
      path: '{{ certs_path }}/{{ inventory_hostname }}.csr'
      privatekey_path: '{{ certs_path }}/private/{{ inventory_hostname }}.key'
      common_name: '{{ inventory_hostname }}'
      owner: '{{ web_server_user }}'

  - name: Create certificates for keystore
    openssl_certificate:
      csr_path: '{{ certs_path }}/{{ inventory_hostname }}.csr'
      path: '{{ certs_path }}/certs/{{ inventory_hostname }}.crt'
      privatekey_path: '{{ certs_path }}/private/{{ inventory_hostname }}.key'
      provider: selfsigned
      owner: '{{ web_server_user }}'

  - name: Create link for libssl.so
    file:
      src: /lib/x86_64-linux-gnu/libssl.so.1.0.0
      dest: /lib/x86_64-linux-gnu/libssl.so.10
      state: link
    notify: restart apache

  - name: Create links
    file:
      src: '{{ link_item.src }}'
      dest: '{{ link_item.dest }}'
      state: link
    loop:
      - src: /lib/x86_64-linux-gnu/libssl.so.1.0.0
        dest: /lib/x86_64-linux-gnu/libssl.so.10
      - src: /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
        dest: /lib/x86_64-linux-gnu/libcrypto.so.10
      - src: '{{ apache_dir }}/mods-available/ssl.load'
        dest: '{{ apache_dir }}/mods-enabled/ssl.load'
      - src: '{{ apache_dir }}/mods-available/ssl.conf'
        dest: '{{ apache_dir }}/mods-enabled/ssl.conf'
      - src: '{{ apache_dir }}/mods-available/setenvif.load'
        dest: '{{ apache_dir }}/mods-enabled/setenvif.load'
      - src: '{{ apache_dir }}/mods-available/mime.load'
        dest: '{{ apache_dir }}/mods-enabled/mime.load'
      - src: '{{ apache_dir }}/mods-available/socache_shmcb.load'
        dest: '{{ apache_dir }}/mods-enabled/socache_shmcb.load'
    loop_control:
      loop_var: link_item
    notify: restart apache

  become: True
