---

- name: Create apache links
  file:
    src: '{{ link_item.src }}'
    dest: '{{ link_item.dest }}'
    state: link
  loop:
    - src: '{{ libssl_path }}'
      dest: '{{ libssl_path | dirname }}/libssl.so.10'
    - src: '{{ libcrypto_path }}'
      dest: '{{ libcrypto_path | dirname }}/libcrypto.so.10'
    - src: '{{ apache_dir }}/mods-available/ssl.load'
      dest: '{{ apache_dir }}/mods-enabled/ssl.load'
    - src: '{{ apache_dir }}/mods-available/ssl.conf'
      dest: '{{ apache_dir }}/mods-enabled/ssl.conf'
    - src: '{{ apache_dir }}/mods-available/setenvif.load'
      dest: '{{ apache_dir }}/mods-enabled/setenvif.load'
    - src: '{{ apache_dir }}/mods-available/mime.load'
      dest: '{{ apache_dir }}/mods-enabled/mime.load'
    - src: '{{ apache_dir }}/mods-available/socache_shmcb.load'
      dest: '{{ apache_dir }}/mods-enabled/socache_shmcb.load'
  loop_control:
    loop_var: link_item
  notify: restart apache
  become: true
