---
# file: tasks/dispatcher_configs.yml

- name: Ensure that dispatcher and farm directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ dispatcher_any_location }}'
    - '{{ farms_any_location }}'
  become: true

- name: Ensure that dispatcher configuration files are ok
  template:
    src: '{{ item }}'
    dest: '{{ dispatcher_any_location }}/{{ item | basename | regex_replace("\.j2","") }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0644
  with_fileglob:
    - ../templates/conf.d/dispatcher/*.j2
  become: true
  register: result
  notify:
    - restart apache

- name: Ensure that farms configuration files are ok
  template:
    src: '{{ item }}'
    dest: '{{ farms_any_location }}/{{ item | basename | regex_replace("\.j2","") }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0644
  with_fileglob:
    - ../templates/conf.d/aem-farms/*.j2
  become: true
  register: result
  notify:
    - restart apache
