---
# file: tasks/dispatcher_configs.yml

- name: Ensure that 'conf' directory exists
  file:
    path: '{{ apache_dir }}/conf'
    state: directory
  become: true

- name: ensure that dispatcher configuration files are ok
  template:
    src: '{{ item }}.j2'
    dest: '{{ dispatcher_any_location }}/{{ item }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
  with_items:
    - '{{ dispatcher_config_set }}'
  become: true
  register: result

- name: restart apache
  debug: msg="trigger apache-restart"
  notify:
    - restart apache
  changed_when: true
  when: result is changed
