---
# file: tasks/install.yml

- name: 'ensure that {{ dispatcher_root }} path is ready'
  file:
    path: '{{ dispatcher_root }}'
#    owner: '{{ web_server_user }}'
#    group: '{{ web_server_group }}'
    state: directory
    mode: 0755
#  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: Create link to modules directory
  file:
    src: /usr/lib/apache2/modules
    dest: /etc/apache2/modules
    state: link
#  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: Ensure that 'conf' directory exists
  file:
    path: '{{ apache_dir }}/conf'
    state: directory
#  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: ensure that mod_dispatcher.so is present
  get_url:
    url: '{{ ftp_server_link }}'
    dest: '/usr/lib/apache2/modules/mod_dispatcher.so'
    owner: 'root'
    group: 'root'
    mode: 0755
  become: True

- name: Allow apache to load module
  sefcontext:
    target: "/etc/{{ ( ansible_os_family == 'Debian' ) | ternary( 'apache2','httpd' ) }}/modules/mod_dispatcher.so"
    setype: httpd_sys_script_exec_t
    state: present
  when:
    - ansible_selinux.status == 'enabled'
#    - ansible_selinux.mode != 'disabled'
  become: True

- name: Add dispatcher.load
  template:
    src: 'dispatcher.load.j2'
    dest: '{{ apache_dir }}/mods-available/dispatcher.load'
    owner: 'root'
    group: 'root'
    mode: 0755
  become: True

- name: Enable dispatcher module
  file:
    src: '{{ apache_dir }}/mods-available/dispatcher.load'
    dest: '{{ apache_dir }}/mods-enabled/dispatcher.load'
    state: link
#  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: ensure that dispatcher configuration files are ok
  template:
    src: '{{ item }}.j2'
    dest: '{{ dispatcher_any_location }}/{{ item }}'
    owner: 'root'
    group: 'root'
    mode: 0640
  with_items:
    - '{{ dispatcher_config_set }}'
  become: True
  notify:
    - restart apache

- name: ensure that main dispatcher configuration is ok
  template:
    src: dispatcher.conf.j2
    dest: '{{ apache_dir }}/conf-available/dispatcher.conf'
#    owner: 'root'
#    group: 'root'
    mode: 0755
  become: True

- name: Enable dispatcher configuration
  file:
    src: '{{ apache_dir }}/conf-available/dispatcher.conf'
    dest: '{{ apache_dir }}/conf-enabled/dispatcher.conf'
    state: link
    mode: 0755
  become: True

- name: Create link to logs
  file:
    src: '/var/log/apache2'
    dest: '{{ apache_dir }}/logs'
    state: link
  notify:
  - restart apache
  become: True
- meta: flush_handlers
