---
# file: tasks/install.yml

- name: 'ensure that group {{ web_server_user }} is present'
  group:
    name: '{{ web_server_user }}'
  become: True

- name: 'ensure that user {{ web_server_user }} is present'
  user:
    name: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    comment: "Apache Web-server user"
  become: True

- name: ensure that utils for SELinux managment are installed
  become: True
  package:
    name: policycoreutils-python
    state: present
  register: installed_packages
  until: installed_packages is succeeded

- name: Allow apache to load module
  sefcontext:
    target:  /etc/httpd/modules/mod_dispatcher.so
    setype: httpd_sys_script_exec_t
    state: present
  when:
    - ansible_selinux.status == 'enabled'
#    - ansible_selinux.mode != 'disabled'
  become: True

- name: ensure that centos-release-scl installed
  become: True
  package:
    name: centos-release-scl
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  when: ansible_distribution_version == '6.8'

- name: ensure that httpd web-server is installed
  become: True
  package:
    name: '{{ apache_packages }}'
    state: present
  register: installed_packages
  until: installed_packages is succeeded

- name: ensure that httpd is started
  service:
    name: '{{ apache_service }}'
    enabled: True
    state: started
  become: True
