---
# file: tasks/install.yml

- name: ensure that dispatcher configuration files are ok
  become: True
  template:
    src: '{{ item }}.j2'
    dest: '{{ dispatcher_any_location }}/{{ item }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
  with_items:
    - '{{ dispatcher_config_set }}'
  notify:
  - restart apache
- meta: flush_handlers

- name: 'ensure that {{ dispatcher_root }} path is ready'
  file:
    path: '{{ dispatcher_root }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    state: directory
    mode: 0755
  become: True
  notify:
  - restart apache
- meta: flush_handlers

- name: ensure that dispatcher module is present
  get_url:
    url: '{{ ftp_server_link }}'
    dest: '{{ apache_dir }}/modules/mod_dispatcher.so'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
  become: True
  notify:
  - restart apache
- meta: flush_handlers

- name: ensure that main dispatcher configuration is ok
  template:
    src: dispatcher.conf.j2
    dest: '{{ apache_dir }}/conf.d/dispatcher.conf'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
  notify:
  - restart apache
  become: True
- meta: flush_handlers
