---
# file: tasks/install.yml

- name: 'ensure that group {{ webserveruser }} is present'
  group:
    name: '{{ webserveruser }}'
  become: True

- name: 'ensure that user {{ webserveruser }} is present'
  user:
    name: '{{ webserveruser }}'
    group: '{{ webservergroup }}'
    comment: "Apache Web-server user"
  become: True

- name: ensure that utils for SELinux managment are installed
  yum:
    name: policycoreutils-python
  become: True

- name: Allow apache to load module
  sefcontext:
    target:  /etc/httpd/modules/mod_dispatcher.so
    setype: httpd_sys_script_exec_t
    state: present


- name: ensure that centos-release-scl installed
  yum:
    name: centos-release-scl
  when: ansible_distribution_version == '6.8'
  become: True

- name: ensure that httpd web-server is installed
  yum:
    name: '{{ apachepackages }}'
  become: True

- name: ensure that httpd is started
  service:
    name: '{{ apacheservice }}'
    enabled: True
    state: started
  become: True

- name: Enable http port
  firewalld:
    port: 80/tcp
    permanent: True
    state: enabled
  become: True

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  become: True