---
# file: tasks/install.yml

- name: 'ensure that {{ dispatcher_root }} path is ready'
  file:
    path: '{{ dispatcher_root }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    state: directory
    mode: 0750
  when: ansible_facts['os_family'] == 'Debian'
  become: True

#- name: Create link to modules directory
#  file:
#    src: /usr/lib/apache2/modules
#    dest: /etc/apache2/modules
#    state: link
#  when: ansible_facts['os_family'] == 'Debian'
#  become: True

- name: Create 'conf' directory
  file:
    path: '{{ apache_dir }}/conf'
    state: directory
  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: Create 'conf.d' directory
  file:
    path: '{{ apache_dir }}/conf.d'
    state: directory
  when: ansible_facts['os_family'] == 'Debian'
  become: True

- name: ensure that dispatcher module is present
  get_url:
    url: '{{ ftp_server_link }}'
    dest: '{{ apache_dir }}/modules/mod_dispatcher.so'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
  become: True
