---
# file: tasks/install.yml

- name: 'ensure that {{ dispatcher_root }} path is ready'
  file:
    path: '{{ dispatcher_root }}'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    state: directory
    mode: 0750
  become: True

- name: ensure that dispatcher module is present
  get_url:
    url: '{{ ftp_server_link }}'
    dest: '{{ apache_dir }}/modules/mod_dispatcher.so'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    mode: 0755
