---
# file: tasks/install.yml

- name: 'ensure that group {{ web_server_user }} is present'
  group:
    name: '{{ web_server_user }}'
  become: True

- name: 'ensure that user {{ web_server_user }} is present'
  user:
    name: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    comment: "Apache Web-server user"
  become: True

- name: ensure that utils for SELinux managment are installed
  yum:
    name: policycoreutils-python
  become: True

- name: ensure that centos-release-scl installed
  yum:
    name: centos-release-scl
  when: ansible_distribution_version == '6.8'
  become: True

- name: ensure that httpd web-server is installed
  yum:
    name: '{{ apache_packages }}'
  become: True

- name: ensure that httpd is started
  service:
    name: '{{ apache_service }}'
    enabled: True
    state: started
  become: True
