---
# file: tasks/main.yml

- name: Load variables for OS family
  include_vars: '{{ ansible_os_family }}.yml'

- name: install apache
  include: installApache.yml

- name: Configuration of Apache
  include_tasks: configureApache.yml

- name: set facts for dispatcher
  include: set_facts.yml

- name: change dispatcher configs
  include: dispatcher_configs.yml

#- name: check if service was installed before
#  stat:
#    path: '{{ dispatcher_file }}'
#  register: dispatcher_done
#- block:
- name: install Dispatcher
  include: install_dispatcher.yml
#  - name: save successfull installation in file
#    file:
#      path: '{{ dispatcher_file }}'
#      state: touch
#    become: True
#  when: not dispatcher_done.stat.exists

- meta: flush_handlers
