---
# file: tasks/main.yml

- name: set facts for Apache
  include: set_factsApache.yml

- name: install apache
  include: installApache.yml

- name: configure apache
  include: configureApache.yml

- name: Allow apache to load module
  sefcontext:
    target:  /etc/httpd/modules/mod_dispatcher.so
    setype: httpd_sys_script_exec_t
    state: present


- name: set facts
  include: set_facts.yml

- name: check if service was installed before
  stat:
    path: '{{ dispatcher_file }}'
  register: dispatcher_done
- block:
  - name: install Dispatcher
    include: install.yml
  - name: configure Dispatcher
    include: configure.yml
  - name: save successfull installation in file
    file:
      path: '{{ dispatcher_file }}'
      state: touch
  when: not dispatcher_done.stat.exists
