---
# file: tasks/main.yml

- name: Load common variables
  include_vars: main.yml

- name: Load variables for OS family
  include_vars: '{{ ansible_os_family }}.yml'

- name: install apache
  include_tasks: installApache.yml

- name: Configuration of Apache
  include_tasks: configureApache.yml

- name: set facts for dispatcher
  include_tasks: set_facts.yml

- name: change dispatcher configs
  include_tasks: dispatcher_configs.yml

- name: install Dispatcher
  include_tasks: install_dispatcher.yml

- meta: flush_handlers
