---
# file: tasks/main.yml

- name: set facts for Apache
  include: set_factsApache.yml

- name: install apache
  include: installApache.yml

- name: configure apache
  include: configureApache.yml

- name: set facts
  include: set_facts.yml

- name: check if service was installed before
  stat:
    path: '{{ dispatcherfile }}'
  register: dispatcher_done
- block:
  - name: install Dispatcher
    include: install.yml
  - name: configure Dispatcher
    include: configure.yml
  - name: save successfull installation in file
    file:
      path: '{{ dispatcherfile }}'
      state: touch
  when: dispatcher_done.stat.exists == False
