---

- name: Install ssl module for apache
  package:
    name: mod_ssl
    state: present
  register: installed_packages
  until: installed_packages is succeeded
  notify:
  - restart apache
  become: true

- name: ensure that ssl.conf is correct
  become: true
  template:
    src: ssl.conf.j2
    dest: '{{ apache_dir }}/conf.d/ssl.conf'
    owner: '{{ web_server_user }}'
    group: '{{ web_server_group }}'
    backup: true
  notify:
  - restart apache
