---
# file: tasks/set_facts.yml

- name: include version and platform dependend varables set
  include_vars: '{{ apacheversion }}-{{ ansible_distribution }}-{{ ansible_distribution_version[0] }}.yml'

- name: reinitialization of defaults as variables
  set_fact:
    webserveruser: '{{ webserveruser }}'
    webservergroup: '{{ webservergroup }}'
    webserveradminemail: '{{ webserveradminemail }}'
    apacheversion: '{{ apacheversion }}'
    webserverhttpport: '{{ webserverhttpport }}'
    webserverloglevel: '{{ webserverloglevel }}'
    webserverssl: '{{ webserverssl }}'
    webserverhttpsport: '{{ webserverhttpsport }}'

- name: prepare all required variables
  set_fact:
    httpdconffile: '{{ apachedir }}/conf/httpd.conf'
    sslconffile: '{{ apachedir }}/conf.d/ssl.conf'