---
# file: tasks/set_facts.yml

- name: reinitialization of defaults as variables
  set_fact:
    dispatchermoduleversion: '{{ dispatchermoduleversion }}'
    dispatcherroot: '{{ dispatcherroot }}'

- name: variables preparation
  set_fact:
    ftpcommonlink: "ftp://{{ ftplogin }}:{{ ftppassword }}@{{ ftpserver }}\
    /aem-playbook/aem/dispatcher/dispatcher-{{ dispatchermoduleversion }}-apache-{{ apacheversion }}"
    dispatcherfile: /opt/dispatcher.done
    semanageshfile: '{{ dispatcherroot }}/semanage.sh'
    dispatcheranylocation: '{{ apachedir }}/conf'
    dispatcherconfigset:
      - dispatcher.any
      - filters.any
      - invalidate.any
      - renders.any
      - vhosts.any
      - clientheaders.any
    dispatcherback: []

- name: check if dispatcherBack are present
  fail:
    msg: "No dispatcherBack available!"
  when: render is undefined and 'aem_instances' not in group_names

- name: find dispatcherBack for dispatcher without render
  set_fact:
    dispatcherback: "{{ dispatcherback + [ inventory_hostname ] }}"
  when: render is undefined

- name: find dispatcherBack for dispatcher with render
  set_fact:
    dispatcherback: "{{ dispatcherback + [ item ] }}"
  with_items: "{{ render.split(',') }}"
  when: render is defined

- name: rewrite dispatcherBack if it is test docker container
  set_fact:
    dispatcherback: ['localhost']
  when: "inventory_hostname == 'test-docker-dispatcher'"

- name: prepare FTP Link variable (with SSL)
  set_fact:
    ftpserverlink: '{{ ftpcommonlink }}-ssl.so'
  when: webserverssl
- name: prepare FTP Link variable (without SSL)
  set_fact:
    ftpserverlink: '{{ ftpcommonlink }}.so'
  when: not webserverssl