---
# file: tasks/set_facts.yml

- name: include version and platform dependend varables set
  include_vars: '{{ apache_version }}-{{ ansible_distribution }}-{{ ansible_distribution_version[0] }}.yml'

- name: reinitialization of defaults as variables
  set_fact:
    web_server_user: '{{ web_server_user }}'
    web_server_group: '{{ web_server_group }}'
    web_server_admin_email: '{{ web_server_admin_email }}'
    apache_version: '{{ apache_version }}'
    web_server_http_port: '{{ web_server_http_port }}'
    web_server_log_level: '{{ web_server_log_level }}'
    web_server_ssl: '{{ web_server_ssl }}'
    web_server_https_port: '{{ web_server_https_port }}'

- name: prepare all required variables
  set_fact:
    httpd_conf_file: '{{ apache_dir }}/conf/httpd.conf'
    ssl_conf_file: '{{ apache_dir }}/conf.d/ssl.conf'
