---
# file: tasks/set_facts.yml

- name: prepare FTP Link variable (with SSL)
  set_fact:
    ftp_server_link: '{{ ftp_common_link }}-ssl.so'
  when: web_server_ssl

- name: prepare FTP Link variable (without SSL)
  set_fact:
    ftp_server_link: '{{ ftp_common_link }}.so'
  when: not web_server_ssl
